diploma_back_office_tag:
    resource: "@DiplomaBackOfficeBundle/Resources/config/routing/tag.yml"
    prefix:   /tag

diploma_back_office_post:
    resource: "@DiplomaBackOfficeBundle/Resources/config/routing/post.yml"
    prefix:   /post

diploma_back_office_test:
    resource: "@DiplomaBackOfficeBundle/Resources/config/routing/test.yml"
    prefix:   /test

diploma_back_office_question:
    resource: "@DiplomaBackOfficeBundle/Resources/config/routing/question.yml"
    prefix:   /question

diploma_back_office_variant:
    resource: "@DiplomaBackOfficeBundle/Resources/config/routing/variant.yml"
    prefix:   /variant

diploma_back_office_answer:
    resource: "@DiplomaBackOfficeBundle/Resources/config/routing/answer.yml"
    prefix:   /answer

diploma_back_office_homepage:
    path:     /
    defaults: { _controller: "DiplomaBackOfficeBundle:Post:index" }

    # TODO: Specify!
diploma_back_office_profile:
    path:     /
    defaults: { _controller: "DiplomaBackOfficeBundle:Post:index" }
