diploma_back_office_tag:
    resource: "@DiplomaBackOfficeBundle/Resources/config/routing/tag.yml"
    prefix:   /tag

diploma_back_office_post:
    resource: "@DiplomaBackOfficeBundle/Resources/config/routing/post.yml"
    prefix:   /post

diploma_back_office_homepage:
    path:     /
    defaults: { _controller: "DiplomaBackOfficeBundle:Post:index" }

    # TODO: Specify!
diploma_back_office_profile:
    path:     /
    defaults: { _controller: "DiplomaBackOfficeBundle:Post:index" }