services:
    diploma.back_office.menu.voter.request:
        class: Diploma\BackOfficeBundle\Menu\RequestVoter
        arguments:
            - @service_container
        tags:
            - { name: knp_menu.voter }