services:
    diploma.back_office.menu.voter.request:
        class: Diploma\BackOfficeBundle\Menu\RequestVoter
        arguments:
            - @service_container
        tags:
            - { name: knp_menu.voter }
    diploma.back_office.registration.form.type:
        class: Diploma\BackOfficeBundle\Form\RegistrationFormType
        tags:
            - { name: form.type, alias: diploma_user_registration }