file:
    path:     /
    defaults: { _controller: "DiplomaBackOfficeBundle:File:index" }

file_upload:
    path:     /upload
    defaults: { _controller: "DiplomaBackOfficeBundle:File:upload" }


file_show:
    path:     /{id}/show
    defaults: { _controller: "DiplomaBackOfficeBundle:File:show" }

file_new:
    path:     /new
    defaults: { _controller: "DiplomaBackOfficeBundle:File:new" }

file_create:
    path:     /create
    defaults: { _controller: "DiplomaBackOfficeBundle:File:create" }
    methods:  POST

file_edit:
    path:     /{id}/edit
    defaults: { _controller: "DiplomaBackOfficeBundle:File:edit" }

file_update:
    path:     /{id}/update
    defaults: { _controller: "DiplomaBackOfficeBundle:File:update" }
    methods:  [POST, PUT]

file_delete:
    path:     /{id}/delete
    defaults: { _controller: "DiplomaBackOfficeBundle:File:delete" }
    methods:  [POST, DELETE]
