task:
    path:     /
    defaults: { _controller: "DiplomaBackOfficeBundle:Task:index" }

task_show:
    path:     /{id}/show
    defaults: { _controller: "DiplomaBackOfficeBundle:Task:show" }

task_new:
    path:     /new
    defaults: { _controller: "DiplomaBackOfficeBundle:Task:new" }

task_create:
    path:     /create
    defaults: { _controller: "DiplomaBackOfficeBundle:Task:create" }
    methods:  POST

task_edit:
    path:     /{id}/edit
    defaults: { _controller: "DiplomaBackOfficeBundle:Task:edit" }

task_update:
    path:     /{id}/update
    defaults: { _controller: "DiplomaBackOfficeBundle:Task:update" }
    methods:  [POST, PUT]

task_delete:
    path:     /{id}/delete
    defaults: { _controller: "DiplomaBackOfficeBundle:Task:delete" }
    methods:  [POST, DELETE]

task_make:
    path:     /{id}/make
    defaults: { _controller: "DiplomaBackOfficeBundle:Task:make" }

task_answer:
    path:     /{id}/answer
    defaults: { _controller: "DiplomaBackOfficeBundle:Task:answer" }

task_mark:
    path:     /{id}/mark
    defaults: { _controller: "DiplomaBackOfficeBundle:Task:mark" }